using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
namespace RockEngine.CodeGenerator
{
    [Generator]
    public class UIHandlerRegistryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var handlerClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                    transform: static (ctx, _) => GetHandlerType(ctx))
                .Where(static m => m is not null);

            var compilationAndHandlers = context.CompilationProvider.Combine(handlerClasses.Collect());

            context.RegisterSourceOutput(compilationAndHandlers,
                static (spc, source) => GenerateRegistry(source.Left, source.Right, spc));
        }

        private static INamedTypeSymbol? GetHandlerType(GeneratorSyntaxContext ctx)
        {
            var classDecl = (ClassDeclarationSyntax)ctx.Node;
            if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            {
                return null;
            }

            // Look for [PropertyHandler] attribute
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.Name == "PropertyHandlerAttribute");
            if (attr == null)
            {
                return null;
            }

            // Must implement IPropertyHandler
            if (!symbol.AllInterfaces.Any(i => i.Name == "IPropertyHandler"))
            {
                return null;
            }

            return symbol;
        }

        private static void GenerateRegistry(Compilation compilation,
      ImmutableArray<INamedTypeSymbol?> handlerSymbols, SourceProductionContext ctx)
        {
            var handlers = handlerSymbols.Where(s => s != null).Distinct(SymbolEqualityComparer.Default);
            var mappings = new List<string>();

            foreach (var handlerSymbol in handlers)
            {
                var attrData = handlerSymbol!.GetAttributes().First(a =>
                    a.AttributeClass?.Name == "PropertyHandlerAttribute");
                var handledTypes = attrData.ConstructorArguments[0].Values
                    .Select(v => v.Value as INamedTypeSymbol)
                    .Where(t => t != null);

                foreach (var handledType in handledTypes)
                {
                    mappings.Add(
                        $$"""{ typeof({{handledType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}}), new {{handlerSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}}() }""");
                }
            }

            var source = $$"""
    // <auto-generated/>
    using System;
    using System.Collections.Generic;
    using RockEngine.Editor.EditorUI.ImGuiRendering.PropertyHandlers;

    namespace RockEngine.Editor.EditorUI.ImGuiRendering
    {
        public static partial class HandlerRegistry
        {
            public static IReadOnlyDictionary<Type, IPropertyHandler> GetAllHandlers()
            {
                return new Dictionary<Type, IPropertyHandler>
                {
                    {{string.Join(",\n                    ", mappings)}}
                };
            }
        }
    }
    """;

            ctx.AddSource("HandlerRegistry.g.cs", source);
        }
    }
}