using System;
using RockEngine.ShaderPreprocessor;

namespace RockEngine.ShaderPreProcessor
{
    public class AnnotationReplacement
    {
        public string NewCode { get; set;}
        /// <summary>Optional metadata generated by this block.</summary>
        public Action<ShaderMetadata> MetadataMutator { get; set; }
    }
}