using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;

namespace RockEngine.CodeGenerator
{
    [Generator]
    public class UIPropertyGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find all class declarations that might be components
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            // Combine the class declarations with the compilation
            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

            // Register the source generator
            context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right, spc));
        }

        private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDecl &&
                   classDecl.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PublicKeyword) ||
                                               m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.InternalKeyword));
        }

        private static ClassDeclarationSyntax GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;

            // Check if the class implements IComponent or has Component attribute
            var semanticModel = context.SemanticModel;
            var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

            // Add type check and cast to INamedTypeSymbol
            if (classSymbol is INamedTypeSymbol namedTypeSymbol && IsComponentClass(namedTypeSymbol))
            {
                return classDeclaration;
            }

            return null;
        }

        private static bool IsComponentClass(INamedTypeSymbol classSymbol)
        {
            // Check if class implements IComponent or has Component attribute
            return (classSymbol.AllInterfaces.Any(i => i.Name == "IComponent") ||
                   classSymbol.GetAttributes().Any(a => a.AttributeClass?.Name == "ComponentAttribute")) && !classSymbol.IsAbstract;
        }

        private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
        {
            if (classes.IsDefaultOrEmpty)
            {
                return;
            }

            foreach (var classDeclaration in classes)
            {
                var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var classSymbol = model.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

                if (classSymbol != null && IsComponentClass(classSymbol))
                {
                    var source = GenerateUIPropertyAccessors(classSymbol, classDeclaration);
                    context.AddSource($"{classSymbol.Name}_UIProperties.g.cs", source);
                }
            }
        }

        private static string GenerateUIPropertyAccessors(INamedTypeSymbol classSymbol, ClassDeclarationSyntax classDecl)
        {
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var properties = GetUIProperties(classSymbol);

            var source = $$"""
            // <auto-generated/>
            #nullable enable
            
            using System;
            using System.Collections.Generic;
            using RockEngine.Core.ECS.Components;
            using RockEngine.Core.Helpers;
            using RockEngine.Core.Attributes;

            namespace {{namespaceName}}
            {
                public partial class {{className}}
                {
                    private static readonly UIPropertyAccessor[] _uiPropertyAccessors = new UIPropertyAccessor[]
                    {
            {{GeneratePropertyAccessors(properties)}}
                    };

                    public static IReadOnlyList<UIPropertyAccessor> GetUIPropertyAccessors() => _uiPropertyAccessors;
                }

                public struct {{className}}PropertyAccess
                {
                    private readonly {{className}} _component;

                    public {{className}}PropertyAccess({{className}} component)
                    {
                        _component = component;
                    }
            {{GeneratePropertyAccessMethods(properties)}}
                }
            }
            """;

            return source;
        }

        private static string GeneratePropertyAccessors(IEnumerable<IPropertySymbol> properties)
        {
            var accessors = new List<string>();

            foreach (var property in properties)
            {
                var uiAttr = property.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "UIEditableAttribute");

                var displayName = uiAttr?.NamedArguments
                    .FirstOrDefault(kvp => kvp.Key == "DisplayName").Value.Value?.ToString() ?? property.Name;

                // Handle nullable types for typeof
                var propertyTypeDisplay = GetTypeForTypeOf(property.Type);

                var accessorCode = $$"""
                            new UIPropertyAccessor(
                                name: "{{property.Name}}",
                                displayName: "{{displayName}}",
                                propertyType: typeof({{propertyTypeDisplay}}),
                                getValue: (component) => (({{property.ContainingType.Name}})component).{{property.Name}},
                                setValue: {{(property.SetMethod != null && property.SetMethod.DeclaredAccessibility == Accessibility.Public ?
                                        $"(component, value) => (({property.ContainingType.Name})component).{property.Name} = ({property.Type.ToDisplayString()})value" : "null")}},
                                canWrite: {{(property.SetMethod != null && property.SetMethod.DeclaredAccessibility == Accessibility.Public).ToString().ToLower()}},
                                attributes: new Attribute[] 
                                {
                                    {{GetAttributeInitializers(property)}}
                                }
                            )
            """;

                accessors.Add(accessorCode);
            }

            return string.Join(",\n", accessors);
        }

        private static string GetTypeForTypeOf(ITypeSymbol typeSymbol)
        {
            // Handle nullable types by getting the non-nullable underlying type
            var nonNullableType = typeSymbol.NullableAnnotation == NullableAnnotation.Annotated
                ? typeSymbol.WithNullableAnnotation(NullableAnnotation.None)
                : typeSymbol;

            // Handle System.Nullable<T> (value types)
            if (nonNullableType is INamedTypeSymbol { IsGenericType: true } genericType &&
                genericType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            {
                nonNullableType = genericType.TypeArguments[0];
            }

            return nonNullableType.ToDisplayString();
        }

        private static string GeneratePropertyAccessMethods(IEnumerable<IPropertySymbol> properties)
        {
            var methods = new List<string>();

            foreach (var property in properties)
            {
                methods.Add($$"""
                    public {{property.Type.ToDisplayString()}} Get{{property.Name}}() => _component.{{property.Name}};
            """);

                if (property.SetMethod != null && property.SetMethod.DeclaredAccessibility == Accessibility.Public)
                {
                    methods.Add($$"""
                    public void Set{{property.Name}}({{property.Type.ToDisplayString()}} value) => _component.{{property.Name}} = value;
                """);
                }
            }

            return string.Join("\n", methods);
        }

        // Update GetAttributeInitializers method in UIPropertyGenerator
        private static string GetAttributeInitializers(IPropertySymbol property)
        {
            var attributes = property.GetAttributes()
                .Where(a => a.AttributeClass?.Name == "RangeAttribute" ||
                           a.AttributeClass?.Name == "ColorAttribute" ||
                           a.AttributeClass?.Name == "StepAttribute") // Add StepAttribute
                .Select(attr =>
                {
                    if (attr.AttributeClass?.Name == "RangeAttribute")
                    {
                        var min = GetRangeValue(attr.ConstructorArguments[0]);
                        var max = GetRangeValue(attr.ConstructorArguments[1]);
                        return $"new RangeAttribute({min}, {max})";
                    }
                    else if (attr.AttributeClass?.Name == "ColorAttribute")
                    {
                        return "new ColorAttribute()";
                    }
                    else if (attr.AttributeClass?.Name == "StepAttribute")
                    {
                        var step = GetStepValue(attr.ConstructorArguments[0]);
                        return $"new StepAttribute({step})";
                    }
                    return null;
                })
                .Where(a => a != null);

            return string.Join(", ", attributes);
        }

        // Add helper method for StepAttribute values
        private static string GetStepValue(TypedConstant constant)
        {
            if (constant.Value == null)
            {
                return "0.1f";
            }

            if (constant.Type?.SpecialType == SpecialType.System_Single)
            {
                float floatValue = (float)constant.Value;
                return FormatFloatLiteral(floatValue);
            }

            return $"{constant.Value}f";
        }

        private static string GetRangeValue(TypedConstant constant)
        {
            if (constant.Value == null)
            {
                return "0f";
            }

            // Check if this represents float.MaxValue
            if (IsFloatMaxValue(constant))
            {
                return "float.MaxValue";
            }

            if (IsFloatMinValue(constant))
            {
                return "float.MinValue";
            }

            // Convert the value to a proper C# float literal
            if (constant.Type?.SpecialType == SpecialType.System_Single)
            {
                float floatValue = (float)constant.Value;
                return FormatFloatLiteral(floatValue);
            }

            // Fallback for other numeric types
            return $"{constant.Value}f";
        }

        private static bool IsFloatMaxValue(TypedConstant constant)
        {
            if (constant.Value is float floatValue)
            {
                return floatValue == float.MaxValue;
            }

            if (constant.Value is double doubleValue)
            {
                return doubleValue >= 3.4028234663852886e38;
            }

            return false;
        }

        private static bool IsFloatMinValue(TypedConstant constant)
        {
            if (constant.Value is float floatValue)
            {
                return floatValue == float.MinValue;
            }

            if (constant.Value is double doubleValue)
            {
                return doubleValue <= -3.4028234663852886e38;
            }

            return false;
        }

        private static string FormatFloatLiteral(float value)
        {
            // Use invariant culture to ensure decimal point instead of comma
            var stringValue = value.ToString("G9", CultureInfo.InvariantCulture);

            // Ensure it has the 'f' suffix
            if (!stringValue.EndsWith("f", StringComparison.OrdinalIgnoreCase))
            {
                stringValue += "f";
            }

            return stringValue;
        }

        private static IEnumerable<IPropertySymbol> GetUIProperties(INamedTypeSymbol classSymbol)
        {
            return classSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.GetMethod != null &&
                           p.GetMethod.DeclaredAccessibility == Accessibility.Public &&
                           !p.IsStatic &&
                           !p.GetAttributes().Any(a => a.AttributeClass?.Name == "SerializeIgnoreAttribute"));
        }
    }
}